blank_issues_enabled: false
contact_links:
   - name: GitHub Action "setup-aws-iam-authenticator" Support
     url: https://github.com/mostafahussein/setup-aws-iam-authenticator
     about: Please ask and answer questions here.
